/* Generated By:JavaCC: Do not edit this line. CreateConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CreateConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CTCMD = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int TNAME = 9;
  /** RegularExpression Id. */
  int OBRA = 10;
  /** RegularExpression Id. */
  int CBRA = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int COMMENT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"Create Table\"",
    "<NUMBER>",
    "<TNAME>",
    "<OBRA>",
    "<CBRA>",
    "\",\"",
    "<COMMENT>",
  };

}
